/**
 * @file Nutrition Constants
 * Shared constants for nutrition components
 */

import { MealFood } from "@/src/shared/services";
import { Coffee, Sun, Sunset, Cookie } from "lucide-react";

export const PRESET_FOODS: Record<string, MealFood[]> = {
  Proteins: [
    { id: "p1", name: "Chicken Breast (100g)", calories: 165, protein: 31, carbs: 0, fat: 3.6, portion: "100g" },
    { id: "p2", name: "Salmon Fillet (100g)", calories: 208, protein: 20, carbs: 0, fat: 13, portion: "100g", vitamins: { vitaminD: 988, vitaminB12: 4.9, niacin: 8.6, vitaminB6: 0.6 }, minerals: { selenium: 41.4, phosphorus: 200, potassium: 363 } },
    { id: "p3", name: "Eggs (2 large)", calories: 156, protein: 13, carbs: 1, fat: 11, portion: "2 eggs", vitamins: { vitaminD: 87, vitaminB12: 0.9, riboflavin: 0.5, folate: 44 }, minerals: { selenium: 30.7, phosphorus: 198, zinc: 1.3 } },
    { id: "p4", name: "Greek Yogurt (150g)", calories: 100, protein: 17, carbs: 6, fat: 0.7, portion: "150g" },
    { id: "p5", name: "Lean Beef (100g)", calories: 250, protein: 26, carbs: 0, fat: 15, portion: "100g" },
    { id: "p6", name: "Tuna (100g)", calories: 132, protein: 28, carbs: 0, fat: 1.3, portion: "100g" },
    { id: "p7", name: "Tofu (100g)", calories: 76, protein: 8, carbs: 2, fat: 4.8, portion: "100g" },
    { id: "p8", name: "Whey Protein (30g)", calories: 120, protein: 24, carbs: 3, fat: 1.5, portion: "1 scoop" },
    { id: "p9", name: "Turkey Breast (100g)", calories: 135, protein: 30, carbs: 0, fat: 1, portion: "100g" },
    { id: "p10", name: "Pork Tenderloin (100g)", calories: 143, protein: 26, carbs: 0, fat: 3.5, portion: "100g" },
    { id: "p11", name: "Cod (100g)", calories: 82, protein: 18, carbs: 0, fat: 0.7, portion: "100g" },
    { id: "p12", name: "Shrimp (100g)", calories: 99, protein: 24, carbs: 0.2, fat: 0.3, portion: "100g" },
    { id: "p13", name: "Chicken Thigh (100g)", calories: 209, protein: 26, carbs: 0, fat: 10, portion: "100g" },
    { id: "p14", name: "Lentils (100g cooked)", calories: 116, protein: 9, carbs: 20, fat: 0.4, portion: "100g" },
    { id: "p15", name: "Chickpeas (100g cooked)", calories: 164, protein: 8.9, carbs: 27, fat: 2.6, portion: "100g" },
    { id: "p16", name: "Black Beans (100g cooked)", calories: 132, protein: 8.9, carbs: 24, fat: 0.5, portion: "100g" },
    { id: "p17", name: "Kidney Beans (100g cooked)", calories: 127, protein: 8.7, carbs: 23, fat: 0.5, portion: "100g" },
    { id: "p18", name: "Edamame (100g)", calories: 122, protein: 11, carbs: 10, fat: 5.2, portion: "100g" },
    { id: "p19", name: "Tempeh (100g)", calories: 193, protein: 19, carbs: 9, fat: 11, portion: "100g" },
    { id: "p20", name: "Seitan (100g)", calories: 370, protein: 75, carbs: 14, fat: 1.9, portion: "100g" },
    { id: "p21", name: "Cottage Cheese (100g)", calories: 98, protein: 11, carbs: 3.4, fat: 4.3, portion: "100g" },
    { id: "p22", name: "Greek Yogurt (100g)", calories: 59, protein: 10, carbs: 3.6, fat: 0.4, portion: "100g" },
    { id: "p23", name: "Egg Whites (100g)", calories: 52, protein: 11, carbs: 0.7, fat: 0.2, portion: "100g" },
    { id: "p24", name: "Sardines (100g)", calories: 208, protein: 25, carbs: 0, fat: 11, portion: "100g" },
    { id: "p25", name: "Mackerel (100g)", calories: 205, protein: 19, carbs: 0, fat: 14, portion: "100g" },
    { id: "p26", name: "Lamb (100g)", calories: 294, protein: 25, carbs: 0, fat: 21, portion: "100g" },
    { id: "p27", name: "Duck Breast (100g)", calories: 201, protein: 23, carbs: 0, fat: 11, portion: "100g" },
    { id: "p28", name: "Veal (100g)", calories: 172, protein: 24, carbs: 0, fat: 8, portion: "100g" },
    { id: "p29", name: "Bison (100g)", calories: 143, protein: 28, carbs: 0, fat: 2.4, portion: "100g" },
    { id: "p30", name: "Venison (100g)", calories: 158, protein: 30, carbs: 0, fat: 3.2, portion: "100g" },
    { id: "p31", name: "Chicken Wings (100g)", calories: 203, protein: 18, carbs: 0, fat: 14, portion: "100g" },
    { id: "p32", name: "Pork Chop (100g)", calories: 231, protein: 25, carbs: 0, fat: 14, portion: "100g" },
    { id: "p33", name: "Ground Turkey (100g)", calories: 170, protein: 21, carbs: 0, fat: 9, portion: "100g" },
    { id: "p34", name: "Ground Beef (100g)", calories: 254, protein: 17, carbs: 0, fat: 20, portion: "100g" },
    { id: "p35", name: "Bacon (3 slices)", calories: 161, protein: 12, carbs: 0.4, fat: 12, portion: "3 slices" },
    { id: "p36", name: "Ham (100g)", calories: 145, protein: 21, carbs: 1.5, fat: 6, portion: "100g" },
    { id: "p37", name: "Sausage (1 link)", calories: 196, protein: 10, carbs: 1, fat: 17, portion: "1 link" },
    { id: "p38", name: "Pepperoni (30g)", calories: 141, protein: 6, carbs: 0.7, fat: 13, portion: "30g" },
    { id: "p39", name: "Salami (30g)", calories: 119, protein: 6, carbs: 0.3, fat: 10, portion: "30g" },
  ],
  Seafood: [
    { id: "sf1", name: "Lobster (100g)", calories: 89, protein: 19, carbs: 0, fat: 0.9, portion: "100g" },
    { id: "sf2", name: "Crab (100g)", calories: 97, protein: 19, carbs: 0, fat: 1.5, portion: "100g" },
    { id: "sf3", name: "Scallops (100g)", calories: 111, protein: 21, carbs: 3, fat: 1, portion: "100g" },
    { id: "sf4", name: "Mussels (100g)", calories: 86, protein: 12, carbs: 3.7, fat: 2.2, portion: "100g" },
    { id: "sf5", name: "Oysters (100g)", calories: 81, protein: 9, carbs: 5, fat: 2.5, portion: "100g" },
    { id: "sf6", name: "Clams (100g)", calories: 74, protein: 13, carbs: 2.6, fat: 1, portion: "100g" },
    { id: "sf7", name: "Calamari (100g)", calories: 175, protein: 18, carbs: 7.8, fat: 7.5, portion: "100g" },
    { id: "sf8", name: "Octopus (100g)", calories: 82, protein: 15, carbs: 2.2, fat: 1, portion: "100g" },
    { id: "sf9", name: "Tilapia (100g)", calories: 96, protein: 20, carbs: 0, fat: 1.7, portion: "100g" },
    { id: "sf10", name: "Sea Bass (100g)", calories: 97, protein: 18, carbs: 0, fat: 2, portion: "100g" },
    { id: "sf11", name: "Swordfish (100g)", calories: 144, protein: 20, carbs: 0, fat: 6.7, portion: "100g" },
    { id: "sf12", name: "Halibut (100g)", calories: 111, protein: 21, carbs: 0, fat: 2.3, portion: "100g" },
    { id: "sf13", name: "Trout (100g)", calories: 148, protein: 21, carbs: 0, fat: 6.6, portion: "100g" },
    { id: "sf14", name: "Anchovies (30g)", calories: 55, protein: 9, carbs: 0, fat: 2, portion: "30g" },
    { id: "sf15", name: "Prawns (100g)", calories: 71, protein: 17, carbs: 0, fat: 0.5, portion: "100g" },
    { id: "sf16", name: "Catfish (100g)", calories: 105, protein: 18, carbs: 0, fat: 2.9, portion: "100g" },
    { id: "sf17", name: "Crayfish (100g)", calories: 82, protein: 16, carbs: 0, fat: 1.2, portion: "100g" },
    { id: "sf18", name: "Sushi Salmon (2 pieces)", calories: 93, protein: 5, carbs: 12, fat: 2.5, portion: "2 pieces" },
    { id: "sf19", name: "Sashimi Tuna (5 slices)", calories: 92, protein: 20, carbs: 0, fat: 1, portion: "5 slices" },
    { id: "sf20", name: "Fish Sticks (4 pieces)", calories: 210, protein: 10, carbs: 18, fat: 11, portion: "4 pieces" },
  ],
  Fruits: [
    { id: "fr1", name: "Apple (medium)", calories: 95, protein: 0.5, carbs: 25, fat: 0.3, portion: "1 medium" },
    { id: "fr2", name: "Banana (medium)", calories: 105, protein: 1.3, carbs: 27, fat: 0.4, portion: "1 medium" },
    { id: "fr3", name: "Orange (medium)", calories: 62, protein: 1.2, carbs: 15, fat: 0.2, portion: "1 medium", fiber: 3.1, vitamins: { vitaminC: 70, folate: 40, thiamin: 0.1 }, minerals: { calcium: 52, potassium: 237 } },
    { id: "fr4", name: "Strawberries (100g)", calories: 32, protein: 0.7, carbs: 8, fat: 0.3, portion: "100g" },
    { id: "fr5", name: "Blueberries (100g)", calories: 57, protein: 0.7, carbs: 14, fat: 0.3, portion: "100g" },
    { id: "fr6", name: "Grapes (100g)", calories: 69, protein: 0.7, carbs: 18, fat: 0.2, portion: "100g" },
    { id: "fr7", name: "Mango (100g)", calories: 60, protein: 0.8, carbs: 15, fat: 0.4, portion: "100g" },
    { id: "fr8", name: "Pineapple (100g)", calories: 50, protein: 0.5, carbs: 13, fat: 0.1, portion: "100g" },
    { id: "fr9", name: "Watermelon (100g)", calories: 30, protein: 0.6, carbs: 8, fat: 0.2, portion: "100g" },
    { id: "fr10", name: "Kiwi (medium)", calories: 42, protein: 0.8, carbs: 10, fat: 0.4, portion: "1 medium" },
    { id: "fr11", name: "Peach (medium)", calories: 59, protein: 1.4, carbs: 14, fat: 0.4, portion: "1 medium" },
    { id: "fr12", name: "Pear (medium)", calories: 101, protein: 0.7, carbs: 27, fat: 0.2, portion: "1 medium" },
    { id: "fr13", name: "Cherries (100g)", calories: 63, protein: 1, carbs: 16, fat: 0.2, portion: "100g" },
    { id: "fr14", name: "Raspberries (100g)", calories: 52, protein: 1.2, carbs: 12, fat: 0.7, portion: "100g" },
    { id: "fr15", name: "Blackberries (100g)", calories: 43, protein: 1.4, carbs: 10, fat: 0.5, portion: "100g" },
    { id: "fr16", name: "Cantaloupe (100g)", calories: 34, protein: 0.8, carbs: 8, fat: 0.2, portion: "100g" },
    { id: "fr17", name: "Honeydew (100g)", calories: 36, protein: 0.5, carbs: 9, fat: 0.1, portion: "100g" },
    { id: "fr18", name: "Papaya (100g)", calories: 43, protein: 0.5, carbs: 11, fat: 0.3, portion: "100g" },
    { id: "fr19", name: "Pomegranate (100g)", calories: 83, protein: 1.7, carbs: 19, fat: 1.2, portion: "100g" },
    { id: "fr20", name: "Grapefruit (medium)", calories: 52, protein: 1, carbs: 13, fat: 0.2, portion: "1 medium" },
    { id: "fr21", name: "Plum (medium)", calories: 30, protein: 0.5, carbs: 8, fat: 0.2, portion: "1 medium" },
    { id: "fr22", name: "Apricot (medium)", calories: 17, protein: 0.5, carbs: 4, fat: 0.1, portion: "1 medium" },
    { id: "fr23", name: "Coconut (100g)", calories: 354, protein: 3.3, carbs: 15, fat: 33, portion: "100g" },
    { id: "fr24", name: "Avocado (medium)", calories: 234, protein: 3, carbs: 12, fat: 21, portion: "1 medium" },
    { id: "fr25", name: "Lemon (medium)", calories: 17, protein: 0.6, carbs: 5, fat: 0.2, portion: "1 medium" },
    { id: "fr26", name: "Lime (medium)", calories: 20, protein: 0.5, carbs: 7, fat: 0.1, portion: "1 medium" },
    { id: "fr27", name: "Tangerine (medium)", calories: 47, protein: 0.7, carbs: 12, fat: 0.2, portion: "1 medium" },
    { id: "fr28", name: "Clementine (medium)", calories: 35, protein: 0.6, carbs: 9, fat: 0.1, portion: "1 medium" },
    { id: "fr29", name: "Mandarin (medium)", calories: 40, protein: 0.6, carbs: 10, fat: 0.2, portion: "1 medium" },
    { id: "fr30", name: "Nectarine (medium)", calories: 62, protein: 1.5, carbs: 15, fat: 0.5, portion: "1 medium" },
    { id: "fr31", name: "Dragon Fruit (100g)", calories: 60, protein: 1.2, carbs: 13, fat: 0.4, portion: "100g" },
    { id: "fr32", name: "Passion Fruit (100g)", calories: 97, protein: 2.2, carbs: 23, fat: 0.7, portion: "100g" },
    { id: "fr33", name: "Guava (100g)", calories: 68, protein: 2.6, carbs: 14, fat: 1, portion: "100g" },
    { id: "fr34", name: "Lychee (100g)", calories: 66, protein: 0.8, carbs: 17, fat: 0.4, portion: "100g" },
    { id: "fr35", name: "Rambutan (100g)", calories: 68, protein: 0.9, carbs: 16, fat: 0.2, portion: "100g" },
    { id: "fr36", name: "Star Fruit (100g)", calories: 31, protein: 1, carbs: 7, fat: 0.3, portion: "100g" },
    { id: "fr37", name: "Persimmon (medium)", calories: 118, protein: 1, carbs: 31, fat: 0.4, portion: "1 medium" },
    { id: "fr38", name: "Cranberries (100g)", calories: 46, protein: 0.4, carbs: 12, fat: 0.1, portion: "100g" },
    { id: "fr39", name: "Gooseberries (100g)", calories: 44, protein: 0.9, carbs: 10, fat: 0.6, portion: "100g" },
    { id: "fr40", name: "Currants (100g)", calories: 56, protein: 1.4, carbs: 14, fat: 0.2, portion: "100g" },
    { id: "fr41", name: "Elderberries (100g)", calories: 73, protein: 0.7, carbs: 18, fat: 0.5, portion: "100g" },
    { id: "fr42", name: "Mulberries (100g)", calories: 43, protein: 1.4, carbs: 10, fat: 0.4, portion: "100g" },
    { id: "fr43", name: "Boysenberries (100g)", calories: 43, protein: 1, carbs: 10, fat: 0.5, portion: "100g" },
    { id: "fr44", name: "Cranberries Fresh (100g)", calories: 46, protein: 0.4, carbs: 12, fat: 0.1, portion: "100g" },
    { id: "fr45", name: "Coconut Water (100ml)", calories: 19, protein: 0.7, carbs: 4, fat: 0.1, portion: "100ml" },
    { id: "fr46", name: "Jackfruit (100g)", calories: 95, protein: 1.7, carbs: 24, fat: 0.6, portion: "100g" },
    { id: "fr47", name: "Durian (100g)", calories: 147, protein: 1.5, carbs: 27, fat: 5.3, portion: "100g" },
    { id: "fr48", name: "Longan (100g)", calories: 60, protein: 1.3, carbs: 15, fat: 0.1, portion: "100g" },
    { id: "fr49", name: "Mangosteen (100g)", calories: 73, protein: 0.4, carbs: 18, fat: 0.6, portion: "100g" },
    { id: "fr50", name: "Custard Apple (100g)", calories: 101, protein: 1.7, carbs: 25, fat: 0.6, portion: "100g" },
    { id: "fr51", name: "Soursop (100g)", calories: 66, protein: 1, carbs: 17, fat: 0.3, portion: "100g" },
    { id: "fr52", name: "Cherimoya (100g)", calories: 75, protein: 1.6, carbs: 18, fat: 0.7, portion: "100g" },
    { id: "fr53", name: "Feijoa (100g)", calories: 55, protein: 0.6, carbs: 13, fat: 0.4, portion: "100g" },
    { id: "fr54", name: "Kiwano (100g)", calories: 44, protein: 1.8, carbs: 8, fat: 1.3, portion: "100g" },
    { id: "fr55", name: "Tamarind (100g)", calories: 239, protein: 2.8, carbs: 63, fat: 0.6, portion: "100g" },
  ],
  Vegetables: [
    { id: "v1", name: "Broccoli (100g)", calories: 34, protein: 2.8, carbs: 7, fat: 0.4, portion: "100g", fiber: 2.6, vitamins: { vitaminC: 89.2, vitaminK: 101.6, folate: 63, vitaminA: 623 }, minerals: { potassium: 316, calcium: 47, iron: 0.7 } },
    { id: "v2", name: "Spinach (100g)", calories: 23, protein: 2.9, carbs: 3.6, fat: 0.4, portion: "100g", fiber: 2.2, vitamins: { vitaminA: 9377, vitaminC: 28.1, vitaminK: 482.9, folate: 194 }, minerals: { iron: 2.7, magnesium: 79, potassium: 558, calcium: 99 } },
    { id: "v3", name: "Mixed Salad (150g)", calories: 30, protein: 2, carbs: 5, fat: 0.3, portion: "150g" },
    { id: "v4", name: "Bell Peppers (100g)", calories: 31, protein: 1, carbs: 6, fat: 0.3, portion: "100g" },
    { id: "v5", name: "Carrots (100g)", calories: 41, protein: 0.9, carbs: 10, fat: 0.2, portion: "100g" },
    { id: "v6", name: "Tomatoes (100g)", calories: 18, protein: 0.9, carbs: 4, fat: 0.2, portion: "100g" },
    { id: "v7", name: "Cucumber (100g)", calories: 16, protein: 0.7, carbs: 4, fat: 0.1, portion: "100g" },
    { id: "v8", name: "Zucchini (100g)", calories: 17, protein: 1.2, carbs: 3, fat: 0.3, portion: "100g" },
    { id: "v9", name: "Cauliflower (100g)", calories: 25, protein: 1.9, carbs: 5, fat: 0.3, portion: "100g" },
    { id: "v10", name: "Cabbage (100g)", calories: 25, protein: 1.3, carbs: 6, fat: 0.1, portion: "100g" },
    { id: "v11", name: "Kale (100g)", calories: 49, protein: 4.3, carbs: 9, fat: 0.9, portion: "100g" },
    { id: "v12", name: "Lettuce (100g)", calories: 15, protein: 1.4, carbs: 3, fat: 0.2, portion: "100g" },
    { id: "v13", name: "Celery (100g)", calories: 16, protein: 0.7, carbs: 3, fat: 0.2, portion: "100g" },
    { id: "v14", name: "Onions (100g)", calories: 40, protein: 1.1, carbs: 9, fat: 0.1, portion: "100g" },
    { id: "v15", name: "Garlic (100g)", calories: 149, protein: 6.4, carbs: 33, fat: 0.5, portion: "100g" },
    { id: "v16", name: "Mushrooms (100g)", calories: 22, protein: 3.1, carbs: 3.3, fat: 0.3, portion: "100g" },
    { id: "v17", name: "Asparagus (100g)", calories: 20, protein: 2.2, carbs: 4, fat: 0.1, portion: "100g" },
    { id: "v18", name: "Green Beans (100g)", calories: 31, protein: 1.8, carbs: 7, fat: 0.2, portion: "100g" },
    { id: "v19", name: "Peas (100g)", calories: 81, protein: 5.4, carbs: 14, fat: 0.4, portion: "100g" },
    { id: "v20", name: "Corn (100g)", calories: 96, protein: 3.4, carbs: 21, fat: 1.2, portion: "100g" },
    { id: "v21", name: "Potato (100g)", calories: 77, protein: 2, carbs: 17, fat: 0.1, portion: "100g" },
    { id: "v22", name: "Sweet Potato (100g)", calories: 86, protein: 1.6, carbs: 20, fat: 0.1, portion: "100g" },
    { id: "v23", name: "Eggplant (100g)", calories: 25, protein: 1, carbs: 6, fat: 0.2, portion: "100g" },
    { id: "v24", name: "Brussels Sprouts (100g)", calories: 43, protein: 3.4, carbs: 9, fat: 0.3, portion: "100g" },
    { id: "v25", name: "Artichoke (100g)", calories: 47, protein: 3.3, carbs: 11, fat: 0.2, portion: "100g" },
    { id: "v26", name: "Beets (100g)", calories: 43, protein: 1.6, carbs: 10, fat: 0.2, portion: "100g" },
    { id: "v27", name: "Radish (100g)", calories: 16, protein: 0.7, carbs: 3.4, fat: 0.1, portion: "100g" },
    { id: "v28", name: "Turnip (100g)", calories: 28, protein: 0.9, carbs: 6, fat: 0.1, portion: "100g" },
    { id: "v29", name: "Pumpkin (100g)", calories: 26, protein: 1, carbs: 7, fat: 0.1, portion: "100g" },
    { id: "v30", name: "Squash (100g)", calories: 16, protein: 1.2, carbs: 3.4, fat: 0.2, portion: "100g" },
    { id: "v31", name: "Okra (100g)", calories: 33, protein: 1.9, carbs: 7, fat: 0.2, portion: "100g" },
    { id: "v32", name: "Leek (100g)", calories: 61, protein: 1.5, carbs: 14, fat: 0.3, portion: "100g" },
    { id: "v33", name: "Fennel (100g)", calories: 31, protein: 1.2, carbs: 7, fat: 0.2, portion: "100g" },
    { id: "v34", name: "Bok Choy (100g)", calories: 13, protein: 1.5, carbs: 2.2, fat: 0.2, portion: "100g" },
    { id: "v35", name: "Collard Greens (100g)", calories: 32, protein: 3, carbs: 6, fat: 0.6, portion: "100g" },
    { id: "v36", name: "Swiss Chard (100g)", calories: 19, protein: 1.8, carbs: 3.7, fat: 0.2, portion: "100g" },
    { id: "v37", name: "Watercress (100g)", calories: 11, protein: 2.3, carbs: 1.3, fat: 0.1, portion: "100g" },
    { id: "v38", name: "Arugula (100g)", calories: 25, protein: 2.6, carbs: 3.7, fat: 0.7, portion: "100g" },
    { id: "v39", name: "Parsnip (100g)", calories: 75, protein: 1.2, carbs: 18, fat: 0.3, portion: "100g" },
    { id: "v40", name: "Jalape\u00f1o (1 pepper)", calories: 4, protein: 0.1, carbs: 0.9, fat: 0, portion: "1 pepper" },
  ],
  Salads: [
    { id: "sal1", name: "Caesar Salad (1 serving)", calories: 358, protein: 14, carbs: 18, fat: 26, portion: "1 serving" },
    { id: "sal2", name: "Greek Salad (1 serving)", calories: 230, protein: 8, carbs: 12, fat: 17, portion: "1 serving" },
    { id: "sal3", name: "Cobb Salad (1 serving)", calories: 430, protein: 30, carbs: 10, fat: 30, portion: "1 serving" },
    { id: "sal4", name: "Garden Salad (1 serving)", calories: 70, protein: 3, carbs: 12, fat: 1, portion: "1 serving" },
    { id: "sal5", name: "Caprese Salad (1 serving)", calories: 280, protein: 14, carbs: 6, fat: 22, portion: "1 serving" },
    { id: "sal6", name: "Waldorf Salad (1 serving)", calories: 340, protein: 4, carbs: 18, fat: 28, portion: "1 serving" },
    { id: "sal7", name: "Nicoise Salad (1 serving)", calories: 360, protein: 22, carbs: 18, fat: 22, portion: "1 serving" },
    { id: "sal8", name: "Tabbouleh (1 serving)", calories: 160, protein: 4, carbs: 18, fat: 8, portion: "1 serving" },
    { id: "sal9", name: "Coleslaw (1 serving)", calories: 178, protein: 1.5, carbs: 14, fat: 13, portion: "1 serving" },
    { id: "sal10", name: "Chicken Caesar Salad (1 serving)", calories: 470, protein: 36, carbs: 18, fat: 28, portion: "1 serving" },
    { id: "sal11", name: "Tuna Salad (1 serving)", calories: 383, protein: 33, carbs: 3, fat: 19, portion: "1 serving" },
    { id: "sal12", name: "Egg Salad (1 serving)", calories: 305, protein: 14, carbs: 3, fat: 26, portion: "1 serving" },
    { id: "sal13", name: "Quinoa Salad (1 serving)", calories: 250, protein: 8, carbs: 34, fat: 9, portion: "1 serving" },
    { id: "sal14", name: "Pasta Salad (1 serving)", calories: 360, protein: 8, carbs: 42, fat: 17, portion: "1 serving" },
    { id: "sal15", name: "Potato Salad (1 serving)", calories: 358, protein: 7, carbs: 28, fat: 24, portion: "1 serving" },
    { id: "sal16", name: "Fruit Salad (1 serving)", calories: 125, protein: 1.5, carbs: 31, fat: 0.5, portion: "1 serving" },
    { id: "sal17", name: "Bean Salad (1 serving)", calories: 220, protein: 10, carbs: 30, fat: 6, portion: "1 serving" },
    { id: "sal18", name: "Asian Sesame Salad (1 serving)", calories: 280, protein: 8, carbs: 20, fat: 18, portion: "1 serving" },
    { id: "sal19", name: "Kale Caesar Salad (1 serving)", calories: 310, protein: 10, carbs: 16, fat: 24, portion: "1 serving" },
    { id: "sal20", name: "Fattoush Salad (1 serving)", calories: 210, protein: 5, carbs: 22, fat: 12, portion: "1 serving" },
  ],
  Nuts: [
    { id: "n1", name: "Almonds (30g)", calories: 173, protein: 6, carbs: 6, fat: 15, portion: "30g" },
    { id: "n2", name: "Walnuts (30g)", calories: 196, protein: 4.5, carbs: 4, fat: 20, portion: "30g" },
    { id: "n3", name: "Cashews (30g)", calories: 157, protein: 5, carbs: 9, fat: 12, portion: "30g" },
    { id: "n4", name: "Pistachios (30g)", calories: 159, protein: 6, carbs: 8, fat: 13, portion: "30g" },
    { id: "n5", name: "Pecans (30g)", calories: 196, protein: 2.6, carbs: 4, fat: 20, portion: "30g" },
    { id: "n6", name: "Hazelnuts (30g)", calories: 178, protein: 4.2, carbs: 4.7, fat: 17, portion: "30g" },
    { id: "n7", name: "Brazil Nuts (30g)", calories: 186, protein: 4, carbs: 3.5, fat: 19, portion: "30g" },
    { id: "n8", name: "Macadamia Nuts (30g)", calories: 214, protein: 2.2, carbs: 4, fat: 22, portion: "30g" },
    { id: "n9", name: "Peanuts (30g)", calories: 170, protein: 7.3, carbs: 6, fat: 14, portion: "30g" },
    { id: "n10", name: "Pine Nuts (30g)", calories: 201, protein: 4, carbs: 4, fat: 20, portion: "30g" },
    { id: "n11", name: "Chestnuts (30g)", calories: 63, protein: 0.8, carbs: 14, fat: 0.6, portion: "30g" },
    { id: "n12", name: "Mixed Nuts (30g)", calories: 174, protein: 5, carbs: 6, fat: 15, portion: "30g" },
    { id: "n13", name: "Roasted Almonds (30g)", calories: 180, protein: 6, carbs: 5, fat: 16, portion: "30g" },
    { id: "n14", name: "Honey Roasted Peanuts (30g)", calories: 168, protein: 6, carbs: 9, fat: 12, portion: "30g" },
    { id: "n15", name: "Trail Mix (30g)", calories: 137, protein: 4, carbs: 13, fat: 9, portion: "30g" },
    { id: "n16", name: "Candied Pecans (30g)", calories: 195, protein: 2, carbs: 12, fat: 16, portion: "30g" },
    { id: "n17", name: "Salted Cashews (30g)", calories: 163, protein: 5, carbs: 9, fat: 13, portion: "30g" },
    { id: "n18", name: "Wasabi Peanuts (30g)", calories: 155, protein: 6, carbs: 10, fat: 10, portion: "30g" },
    { id: "n19", name: "Tiger Nuts (30g)", calories: 143, protein: 1.5, carbs: 19, fat: 7, portion: "30g" },
    { id: "n20", name: "Coconut Almonds (30g)", calories: 170, protein: 5, carbs: 8, fat: 14, portion: "30g" },
  ],
  "Dry Fruits": [
    { id: "df1", name: "Dates (100g)", calories: 282, protein: 2.5, carbs: 75, fat: 0.4, portion: "100g" },
    { id: "df2", name: "Raisins (100g)", calories: 299, protein: 3.1, carbs: 79, fat: 0.5, portion: "100g" },
    { id: "df3", name: "Prunes (100g)", calories: 240, protein: 2.2, carbs: 64, fat: 0.4, portion: "100g" },
    { id: "df4", name: "Apricots Dried (100g)", calories: 241, protein: 3.4, carbs: 63, fat: 0.5, portion: "100g" },
    { id: "df5", name: "Figs Dried (100g)", calories: 249, protein: 3.3, carbs: 64, fat: 1, portion: "100g" },
    { id: "df6", name: "Cranberries Dried (100g)", calories: 308, protein: 0.1, carbs: 82, fat: 1.4, portion: "100g" },
    { id: "df7", name: "Goji Berries Dried (100g)", calories: 349, protein: 14, carbs: 77, fat: 0.4, portion: "100g" },
    { id: "df8", name: "Mango Dried (100g)", calories: 319, protein: 2.5, carbs: 78, fat: 1.2, portion: "100g" },
    { id: "df9", name: "Banana Chips (100g)", calories: 519, protein: 2.3, carbs: 58, fat: 34, portion: "100g" },
    { id: "df10", name: "Coconut Flakes (100g)", calories: 660, protein: 6.9, carbs: 24, fat: 65, portion: "100g" },
    { id: "df11", name: "Apple Dried (100g)", calories: 243, protein: 0.9, carbs: 66, fat: 0.3, portion: "100g" },
    { id: "df12", name: "Peach Dried (100g)", calories: 239, protein: 3.6, carbs: 61, fat: 0.8, portion: "100g" },
    { id: "df13", name: "Pear Dried (100g)", calories: 262, protein: 1.9, carbs: 70, fat: 0.6, portion: "100g" },
    { id: "df14", name: "Cherries Dried (100g)", calories: 333, protein: 2.1, carbs: 80, fat: 0.7, portion: "100g" },
    { id: "df15", name: "Strawberries Dried (100g)", calories: 317, protein: 2.2, carbs: 77, fat: 1.2, portion: "100g" },
    { id: "df16", name: "Blueberries Dried (100g)", calories: 317, protein: 2.5, carbs: 80, fat: 1.2, portion: "100g" },
    { id: "df17", name: "Pineapple Dried (100g)", calories: 319, protein: 1.2, carbs: 78, fat: 0.9, portion: "100g" },
    { id: "df18", name: "Papaya Dried (100g)", calories: 324, protein: 0.6, carbs: 81, fat: 0.1, portion: "100g" },
    { id: "df19", name: "Kiwi Dried (100g)", calories: 285, protein: 3.3, carbs: 70, fat: 1.1, portion: "100g" },
    { id: "df20", name: "Coconut Chips (100g)", calories: 660, protein: 6.9, carbs: 24, fat: 65, portion: "100g" },
    { id: "df21", name: "Golden Raisins (100g)", calories: 302, protein: 3.1, carbs: 80, fat: 0.5, portion: "100g" },
    { id: "df22", name: "Sultanas (100g)", calories: 299, protein: 3.1, carbs: 79, fat: 0.5, portion: "100g" },
    { id: "df23", name: "Currants Dried (100g)", calories: 283, protein: 4.1, carbs: 74, fat: 0.6, portion: "100g" },
    { id: "df24", name: "Mulberries Dried (100g)", calories: 317, protein: 10, carbs: 70, fat: 2.4, portion: "100g" },
    { id: "df25", name: "Gooseberries Dried (100g)", calories: 285, protein: 0.9, carbs: 73, fat: 0.6, portion: "100g" },
    { id: "df26", name: "Cranberry Raisins (100g)", calories: 308, protein: 0.1, carbs: 82, fat: 1.4, portion: "100g" },
    { id: "df27", name: "Tamarind Dried (100g)", calories: 239, protein: 2.8, carbs: 63, fat: 0.6, portion: "100g" },
    { id: "df28", name: "Jujube Dried (100g)", calories: 281, protein: 3.7, carbs: 73, fat: 0.2, portion: "100g" },
    { id: "df29", name: "Longan Dried (100g)", calories: 286, protein: 4.9, carbs: 74, fat: 0.4, portion: "100g" },
    { id: "df30", name: "Lychee Dried (100g)", calories: 277, protein: 3.8, carbs: 71, fat: 1.2, portion: "100g" },
    { id: "df31", name: "Persimmon Dried (100g)", calories: 274, protein: 0.6, carbs: 73, fat: 0.2, portion: "100g" },
    { id: "df32", name: "Pomegranate Seeds Dried (100g)", calories: 83, protein: 1.7, carbs: 19, fat: 1.2, portion: "100g" },
    { id: "df33", name: "Mixed Dry Fruits (100g)", calories: 300, protein: 3, carbs: 75, fat: 1, portion: "100g" },
  ],
  Seeds: [
    { id: "s1", name: "Chia Seeds (2 tbsp)", calories: 138, protein: 4.7, carbs: 12, fat: 8.7, portion: "2 tbsp", fiber: 10.6, vitamins: { thiamin: 0.2, niacin: 2.5 }, minerals: { calcium: 177, magnesium: 95, phosphorus: 265, manganese: 0.6 } },
    { id: "s2", name: "Flax Seeds (2 tbsp)", calories: 110, protein: 3.8, carbs: 6, fat: 8.5, portion: "2 tbsp" },
    { id: "s3", name: "Sunflower Seeds (30g)", calories: 164, protein: 5.5, carbs: 6, fat: 14, portion: "30g" },
    { id: "s4", name: "Pumpkin Seeds (30g)", calories: 158, protein: 8.5, carbs: 3, fat: 13, portion: "30g" },
    { id: "s5", name: "Sesame Seeds (2 tbsp)", calories: 104, protein: 3.2, carbs: 4, fat: 9, portion: "2 tbsp" },
    { id: "s6", name: "Hemp Seeds (2 tbsp)", calories: 111, protein: 6.3, carbs: 2, fat: 9.5, portion: "2 tbsp" },
    { id: "s7", name: "Poppy Seeds (2 tbsp)", calories: 73, protein: 2.5, carbs: 4, fat: 5.8, portion: "2 tbsp" },
    { id: "s8", name: "Quinoa Seeds (100g cooked)", calories: 120, protein: 4.4, carbs: 22, fat: 1.9, portion: "100g" },
    { id: "s9", name: "Black Sesame Seeds (2 tbsp)", calories: 104, protein: 3.2, carbs: 4, fat: 9, portion: "2 tbsp" },
    { id: "s10", name: "Watermelon Seeds (30g)", calories: 164, protein: 8.5, carbs: 4, fat: 14, portion: "30g" },
    { id: "s11", name: "Basil Seeds (2 tbsp)", calories: 60, protein: 2, carbs: 7, fat: 2.5, portion: "2 tbsp" },
    { id: "s12", name: "Fennel Seeds (1 tbsp)", calories: 20, protein: 0.9, carbs: 3, fat: 0.6, portion: "1 tbsp" },
  ],
  Carbs: [
    { id: "c1", name: "Brown Rice (150g cooked)", calories: 166, protein: 3.5, carbs: 35, fat: 1.5, portion: "150g" },
    { id: "c2", name: "Oatmeal (50g dry)", calories: 190, protein: 7, carbs: 34, fat: 3.5, portion: "50g" },
    { id: "c3", name: "Quinoa (150g cooked)", calories: 180, protein: 6.6, carbs: 29, fat: 3, portion: "150g" },
    { id: "c4", name: "Whole Wheat Bread (2 slices)", calories: 160, protein: 8, carbs: 28, fat: 2, portion: "2 slices" },
    { id: "c5", name: "White Rice (150g cooked)", calories: 205, protein: 4.3, carbs: 45, fat: 0.4, portion: "150g" },
    { id: "c6", name: "Pasta (100g cooked)", calories: 131, protein: 5, carbs: 25, fat: 1.1, portion: "100g" },
    { id: "c7", name: "Whole Wheat Pasta (100g cooked)", calories: 124, protein: 5, carbs: 25, fat: 1.1, portion: "100g" },
    { id: "c8", name: "Barley (100g cooked)", calories: 123, protein: 2.3, carbs: 28, fat: 0.4, portion: "100g" },
    { id: "c9", name: "Bulgur (100g cooked)", calories: 83, protein: 3.1, carbs: 19, fat: 0.2, portion: "100g" },
    { id: "c10", name: "Buckwheat (100g cooked)", calories: 92, protein: 3.4, carbs: 20, fat: 0.6, portion: "100g" },
    { id: "c11", name: "Millet (100g cooked)", calories: 119, protein: 3.5, carbs: 24, fat: 1, portion: "100g" },
    { id: "c12", name: "Wild Rice (100g cooked)", calories: 101, protein: 4, carbs: 21, fat: 0.3, portion: "100g" },
    { id: "c13", name: "Couscous (100g cooked)", calories: 112, protein: 3.8, carbs: 23, fat: 0.2, portion: "100g" },
    { id: "c14", name: "Sweet Potato (150g)", calories: 129, protein: 2, carbs: 30, fat: 0.1, portion: "150g" },
    { id: "c15", name: "Potato (150g)", calories: 116, protein: 3, carbs: 26, fat: 0.2, portion: "150g" },
    { id: "c16", name: "Basmati Rice (150g cooked)", calories: 191, protein: 4, carbs: 42, fat: 0.5, portion: "150g" },
    { id: "c17", name: "Jasmine Rice (150g cooked)", calories: 194, protein: 3.5, carbs: 43, fat: 0.4, portion: "150g" },
    { id: "c18", name: "Soba Noodles (100g cooked)", calories: 99, protein: 5.1, carbs: 21, fat: 0.1, portion: "100g" },
    { id: "c19", name: "Udon Noodles (100g cooked)", calories: 99, protein: 3, carbs: 22, fat: 0.2, portion: "100g" },
    { id: "c20", name: "Egg Noodles (100g cooked)", calories: 138, protein: 5, carbs: 25, fat: 2.1, portion: "100g" },
    { id: "c21", name: "Rice Noodles (100g cooked)", calories: 109, protein: 0.9, carbs: 25, fat: 0.2, portion: "100g" },
    { id: "c22", name: "Corn Tortilla (1 medium)", calories: 52, protein: 1.4, carbs: 11, fat: 0.7, portion: "1 medium" },
    { id: "c23", name: "Flour Tortilla (1 large)", calories: 218, protein: 5.7, carbs: 36, fat: 5, portion: "1 large" },
    { id: "c24", name: "Pita Bread (1 piece)", calories: 165, protein: 5.5, carbs: 33, fat: 0.7, portion: "1 piece" },
    { id: "c25", name: "Naan Bread (1 piece)", calories: 262, protein: 9, carbs: 45, fat: 5, portion: "1 piece" },
  ],
  "Breads & Bakery": [
    { id: "bk1", name: "White Bread (1 slice)", calories: 79, protein: 2.7, carbs: 15, fat: 1, portion: "1 slice" },
    { id: "bk2", name: "Sourdough Bread (1 slice)", calories: 93, protein: 3.8, carbs: 18, fat: 0.6, portion: "1 slice" },
    { id: "bk3", name: "Rye Bread (1 slice)", calories: 83, protein: 2.7, carbs: 15, fat: 1.1, portion: "1 slice" },
    { id: "bk4", name: "Multigrain Bread (1 slice)", calories: 69, protein: 3.5, carbs: 12, fat: 1.1, portion: "1 slice" },
    { id: "bk5", name: "Bagel (1 plain)", calories: 289, protein: 11, carbs: 56, fat: 1.7, portion: "1 bagel" },
    { id: "bk6", name: "Croissant (1 medium)", calories: 231, protein: 5, carbs: 26, fat: 12, portion: "1 medium" },
    { id: "bk7", name: "English Muffin (1 whole)", calories: 132, protein: 5.1, carbs: 26, fat: 1, portion: "1 muffin" },
    { id: "bk8", name: "Ciabatta Roll (1 medium)", calories: 200, protein: 7, carbs: 38, fat: 2, portion: "1 roll" },
    { id: "bk9", name: "Baguette (60g)", calories: 165, protein: 5, carbs: 33, fat: 1, portion: "60g" },
    { id: "bk10", name: "Brioche (1 slice)", calories: 130, protein: 3.5, carbs: 18, fat: 5, portion: "1 slice" },
    { id: "bk11", name: "Focaccia (1 slice)", calories: 175, protein: 4, carbs: 24, fat: 7, portion: "1 slice" },
    { id: "bk12", name: "Cornbread (1 piece)", calories: 198, protein: 4, carbs: 29, fat: 7, portion: "1 piece" },
    { id: "bk13", name: "Flatbread (1 piece)", calories: 168, protein: 5, carbs: 30, fat: 3, portion: "1 piece" },
    { id: "bk14", name: "Garlic Bread (2 slices)", calories: 206, protein: 4, carbs: 24, fat: 10, portion: "2 slices" },
    { id: "bk15", name: "Pumpernickel Bread (1 slice)", calories: 65, protein: 2.3, carbs: 12, fat: 0.8, portion: "1 slice" },
  ],
  "Cereals & Breakfast": [
    { id: "cb1", name: "Granola (50g)", calories: 225, protein: 5.5, carbs: 32, fat: 9, portion: "50g" },
    { id: "cb2", name: "Muesli (50g)", calories: 183, protein: 5, carbs: 33, fat: 3.5, portion: "50g" },
    { id: "cb3", name: "Cornflakes (30g)", calories: 113, protein: 2, carbs: 26, fat: 0.3, portion: "30g" },
    { id: "cb4", name: "Bran Flakes (30g)", calories: 96, protein: 3, carbs: 22, fat: 0.6, portion: "30g" },
    { id: "cb5", name: "Cheerios (30g)", calories: 111, protein: 3, carbs: 22, fat: 2, portion: "30g" },
    { id: "cb6", name: "Oat Bran (30g)", calories: 73, protein: 3.5, carbs: 16, fat: 1, portion: "30g" },
    { id: "cb7", name: "Wheat Bran (30g)", calories: 63, protein: 4.4, carbs: 19, fat: 1.3, portion: "30g" },
    { id: "cb8", name: "Overnight Oats (1 serving)", calories: 310, protein: 11, carbs: 46, fat: 9, portion: "1 serving" },
    { id: "cb9", name: "Pancakes (2 medium)", calories: 356, protein: 8, carbs: 46, fat: 14, portion: "2 pancakes" },
    { id: "cb10", name: "Waffles (2 medium)", calories: 380, protein: 8, carbs: 50, fat: 16, portion: "2 waffles" },
    { id: "cb11", name: "French Toast (2 slices)", calories: 336, protein: 11, carbs: 36, fat: 16, portion: "2 slices" },
    { id: "cb12", name: "Acai Bowl (1 serving)", calories: 380, protein: 6, carbs: 62, fat: 12, portion: "1 serving" },
    { id: "cb13", name: "Smoothie Bowl (1 serving)", calories: 340, protein: 8, carbs: 56, fat: 10, portion: "1 serving" },
    { id: "cb14", name: "Porridge with Milk (1 bowl)", calories: 230, protein: 9, carbs: 36, fat: 5, portion: "1 bowl" },
    { id: "cb15", name: "Granola Bar (1 bar)", calories: 190, protein: 4, carbs: 28, fat: 7, portion: "1 bar" },
  ],
  Fats: [
    { id: "f1", name: "Olive Oil (1 tbsp)", calories: 119, protein: 0, carbs: 0, fat: 13.5, portion: "1 tbsp" },
    { id: "f2", name: "Coconut Oil (1 tbsp)", calories: 117, protein: 0, carbs: 0, fat: 13.6, portion: "1 tbsp" },
    { id: "f3", name: "Avocado Oil (1 tbsp)", calories: 124, protein: 0, carbs: 0, fat: 14, portion: "1 tbsp" },
    { id: "f4", name: "Butter (1 tbsp)", calories: 102, protein: 0.1, carbs: 0, fat: 11.5, portion: "1 tbsp" },
    { id: "f5", name: "Ghee (1 tbsp)", calories: 112, protein: 0, carbs: 0, fat: 12.7, portion: "1 tbsp" },
    { id: "f6", name: "Peanut Butter (2 tbsp)", calories: 188, protein: 8, carbs: 6, fat: 16, portion: "2 tbsp" },
    { id: "f7", name: "Almond Butter (2 tbsp)", calories: 196, protein: 7, carbs: 6, fat: 18, portion: "2 tbsp" },
    { id: "f8", name: "Cashew Butter (2 tbsp)", calories: 188, protein: 6, carbs: 9, fat: 16, portion: "2 tbsp" },
    { id: "f9", name: "Tahini (2 tbsp)", calories: 178, protein: 5, carbs: 6, fat: 16, portion: "2 tbsp" },
    { id: "f10", name: "Sesame Oil (1 tbsp)", calories: 120, protein: 0, carbs: 0, fat: 14, portion: "1 tbsp" },
    { id: "f11", name: "Flaxseed Oil (1 tbsp)", calories: 120, protein: 0, carbs: 0, fat: 14, portion: "1 tbsp" },
    { id: "f12", name: "MCT Oil (1 tbsp)", calories: 115, protein: 0, carbs: 0, fat: 14, portion: "1 tbsp" },
  ],
  Dairy: [
    { id: "d1", name: "Milk (250ml)", calories: 125, protein: 8, carbs: 12, fat: 5, portion: "250ml" },
    { id: "d2", name: "Cottage Cheese (100g)", calories: 98, protein: 11, carbs: 3.4, fat: 4.3, portion: "100g" },
    { id: "d3", name: "Mozzarella (30g)", calories: 85, protein: 6, carbs: 0.6, fat: 6.3, portion: "30g" },
    { id: "d4", name: "Cheddar Cheese (30g)", calories: 113, protein: 7, carbs: 0.4, fat: 9, portion: "30g" },
    { id: "d5", name: "Feta Cheese (30g)", calories: 75, protein: 4, carbs: 1.2, fat: 6, portion: "30g" },
    { id: "d6", name: "Parmesan (30g)", calories: 111, protein: 10, carbs: 1, fat: 7.3, portion: "30g" },
    { id: "d7", name: "Greek Yogurt (100g)", calories: 59, protein: 10, carbs: 3.6, fat: 0.4, portion: "100g" },
    { id: "d8", name: "Regular Yogurt (100g)", calories: 59, protein: 10, carbs: 3.6, fat: 0.4, portion: "100g" },
    { id: "d9", name: "Sour Cream (2 tbsp)", calories: 60, protein: 1, carbs: 1, fat: 6, portion: "2 tbsp" },
    { id: "d10", name: "Cream Cheese (2 tbsp)", calories: 100, protein: 2, carbs: 1, fat: 10, portion: "2 tbsp" },
    { id: "d11", name: "Buttermilk (250ml)", calories: 99, protein: 8, carbs: 12, fat: 2.2, portion: "250ml" },
    { id: "d12", name: "Goat Cheese (30g)", calories: 103, protein: 7, carbs: 0.1, fat: 8, portion: "30g" },
    { id: "d13", name: "Skim Milk (250ml)", calories: 83, protein: 8, carbs: 12, fat: 0.2, portion: "250ml" },
    { id: "d14", name: "Heavy Cream (2 tbsp)", calories: 101, protein: 0.6, carbs: 0.8, fat: 11, portion: "2 tbsp" },
    { id: "d15", name: "Whipped Cream (2 tbsp)", calories: 51, protein: 0.3, carbs: 2, fat: 4.6, portion: "2 tbsp" },
    { id: "d16", name: "Swiss Cheese (30g)", calories: 106, protein: 8, carbs: 1.5, fat: 8, portion: "30g" },
    { id: "d17", name: "Brie (30g)", calories: 95, protein: 6, carbs: 0.1, fat: 8, portion: "30g" },
    { id: "d18", name: "Ricotta (100g)", calories: 174, protein: 11, carbs: 3, fat: 13, portion: "100g" },
    { id: "d19", name: "Mascarpone (2 tbsp)", calories: 120, protein: 2, carbs: 1, fat: 13, portion: "2 tbsp" },
    { id: "d20", name: "Kefir (250ml)", calories: 104, protein: 6, carbs: 12, fat: 3.5, portion: "250ml" },
  ],
  "Sweets & Desserts": [
    // Cookies
    { id: "sw1", name: "Chocolate Chip Cookie (1 medium)", calories: 221, protein: 2.5, carbs: 30, fat: 11, portion: "1 cookie" },
    { id: "sw2", name: "Oatmeal Raisin Cookie (1 medium)", calories: 195, protein: 2.5, carbs: 28, fat: 8, portion: "1 cookie" },
    { id: "sw3", name: "Sugar Cookie (1 medium)", calories: 160, protein: 2, carbs: 24, fat: 7, portion: "1 cookie" },
    { id: "sw4", name: "Peanut Butter Cookie (1 medium)", calories: 200, protein: 4, carbs: 22, fat: 11, portion: "1 cookie" },
    { id: "sw5", name: "Shortbread Cookie (2 pieces)", calories: 176, protein: 2, carbs: 22, fat: 9, portion: "2 pieces" },
    { id: "sw6", name: "Oreo Cookies (3 pieces)", calories: 160, protein: 1.5, carbs: 25, fat: 7, portion: "3 cookies" },
    { id: "sw7", name: "Macaron (1 piece)", calories: 97, protein: 1.5, carbs: 15, fat: 3.5, portion: "1 piece" },
    { id: "sw8", name: "Biscotti (1 piece)", calories: 110, protein: 2, carbs: 16, fat: 4.5, portion: "1 piece" },
    // Cakes
    { id: "sw9", name: "Chocolate Cake (1 slice)", calories: 352, protein: 5, carbs: 50, fat: 14, portion: "1 slice" },
    { id: "sw10", name: "Cheesecake (1 slice)", calories: 401, protein: 7, carbs: 32, fat: 28, portion: "1 slice" },
    { id: "sw11", name: "Carrot Cake (1 slice)", calories: 415, protein: 5, carbs: 52, fat: 22, portion: "1 slice" },
    { id: "sw12", name: "Red Velvet Cake (1 slice)", calories: 367, protein: 5, carbs: 43, fat: 19, portion: "1 slice" },
    { id: "sw13", name: "Pound Cake (1 slice)", calories: 293, protein: 4, carbs: 37, fat: 14, portion: "1 slice" },
    { id: "sw14", name: "Tiramisu (1 serving)", calories: 370, protein: 6, carbs: 35, fat: 22, portion: "1 serving" },
    { id: "sw15", name: "Brownie (1 piece)", calories: 243, protein: 3, carbs: 30, fat: 13, portion: "1 piece" },
    { id: "sw16", name: "Cupcake (1 medium)", calories: 305, protein: 3, carbs: 42, fat: 14, portion: "1 cupcake" },
    { id: "sw17", name: "Angel Food Cake (1 slice)", calories: 129, protein: 3, carbs: 29, fat: 0.2, portion: "1 slice" },
    { id: "sw18", name: "Lemon Drizzle Cake (1 slice)", calories: 320, protein: 4, carbs: 44, fat: 14, portion: "1 slice" },
    // Chocolates
    { id: "sw19", name: "Dark Chocolate 70% (30g)", calories: 170, protein: 2.2, carbs: 13, fat: 12, portion: "30g" },
    { id: "sw20", name: "Milk Chocolate (30g)", calories: 160, protein: 2.2, carbs: 17, fat: 9, portion: "30g" },
    { id: "sw21", name: "White Chocolate (30g)", calories: 166, protein: 1.8, carbs: 17, fat: 10, portion: "30g" },
    { id: "sw22", name: "Chocolate Truffle (2 pieces)", calories: 130, protein: 1.5, carbs: 12, fat: 9, portion: "2 pieces" },
    { id: "sw23", name: "Chocolate Bar (50g)", calories: 267, protein: 3.5, carbs: 28, fat: 15, portion: "50g" },
    { id: "sw24", name: "Nutella (2 tbsp)", calories: 200, protein: 2, carbs: 22, fat: 12, portion: "2 tbsp" },
    { id: "sw25", name: "Hot Chocolate (250ml)", calories: 192, protein: 8, carbs: 27, fat: 6, portion: "250ml" },
    // Pastries
    { id: "sw26", name: "Donut (1 glazed)", calories: 269, protein: 4, carbs: 31, fat: 15, portion: "1 donut" },
    { id: "sw27", name: "Cinnamon Roll (1 medium)", calories: 353, protein: 5, carbs: 48, fat: 16, portion: "1 roll" },
    { id: "sw28", name: "Danish Pastry (1 piece)", calories: 266, protein: 5, carbs: 26, fat: 16, portion: "1 piece" },
    { id: "sw29", name: "Eclair (1 piece)", calories: 239, protein: 4, carbs: 23, fat: 14, portion: "1 piece" },
    { id: "sw30", name: "Muffin Blueberry (1 large)", calories: 350, protein: 5, carbs: 52, fat: 13, portion: "1 muffin" },
    { id: "sw31", name: "Muffin Chocolate (1 large)", calories: 405, protein: 6, carbs: 56, fat: 18, portion: "1 muffin" },
    { id: "sw32", name: "Scone (1 medium)", calories: 275, protein: 5, carbs: 37, fat: 12, portion: "1 scone" },
    { id: "sw33", name: "Baklava (1 piece)", calories: 334, protein: 5, carbs: 29, fat: 23, portion: "1 piece" },
    // Ice Cream & Frozen
    { id: "sw34", name: "Vanilla Ice Cream (1/2 cup)", calories: 207, protein: 3.5, carbs: 24, fat: 11, portion: "1/2 cup" },
    { id: "sw35", name: "Chocolate Ice Cream (1/2 cup)", calories: 216, protein: 3.8, carbs: 25, fat: 11, portion: "1/2 cup" },
    { id: "sw36", name: "Strawberry Ice Cream (1/2 cup)", calories: 192, protein: 3, carbs: 23, fat: 10, portion: "1/2 cup" },
    { id: "sw37", name: "Frozen Yogurt (1/2 cup)", calories: 159, protein: 4, carbs: 28, fat: 4, portion: "1/2 cup" },
    { id: "sw38", name: "Sorbet (1/2 cup)", calories: 130, protein: 0, carbs: 33, fat: 0, portion: "1/2 cup" },
    { id: "sw39", name: "Gelato (1/2 cup)", calories: 204, protein: 4, carbs: 26, fat: 9, portion: "1/2 cup" },
    { id: "sw40", name: "Popsicle (1 bar)", calories: 42, protein: 0, carbs: 11, fat: 0, portion: "1 bar" },
    // Other sweets
    { id: "sw41", name: "Jelly/Jam (1 tbsp)", calories: 56, protein: 0.1, carbs: 14, fat: 0, portion: "1 tbsp" },
    { id: "sw42", name: "Honey (1 tbsp)", calories: 64, protein: 0.1, carbs: 17, fat: 0, portion: "1 tbsp" },
    { id: "sw43", name: "Maple Syrup (1 tbsp)", calories: 52, protein: 0, carbs: 13, fat: 0, portion: "1 tbsp" },
    { id: "sw44", name: "Pudding Chocolate (1 cup)", calories: 208, protein: 4, carbs: 35, fat: 6, portion: "1 cup" },
    { id: "sw45", name: "Rice Pudding (1 cup)", calories: 260, protein: 8, carbs: 42, fat: 6, portion: "1 cup" },
    { id: "sw46", name: "Cr\u00e8me Br\u00fbl\u00e9e (1 serving)", calories: 328, protein: 5, carbs: 28, fat: 22, portion: "1 serving" },
    { id: "sw47", name: "Panna Cotta (1 serving)", calories: 302, protein: 3, carbs: 25, fat: 21, portion: "1 serving" },
    { id: "sw48", name: "Candy Bar Snickers (1 bar)", calories: 280, protein: 4, carbs: 35, fat: 14, portion: "1 bar" },
    { id: "sw49", name: "Gummy Bears (30g)", calories: 100, protein: 2.2, carbs: 23, fat: 0, portion: "30g" },
    { id: "sw50", name: "Marshmallows (4 pieces)", calories: 92, protein: 0.5, carbs: 23, fat: 0, portion: "4 pieces" },
  ],
  Snacks: [
    { id: "sn1", name: "Potato Chips (30g)", calories: 160, protein: 2, carbs: 15, fat: 10, portion: "30g" },
    { id: "sn2", name: "Tortilla Chips (30g)", calories: 142, protein: 2, carbs: 18, fat: 7, portion: "30g" },
    { id: "sn3", name: "Popcorn Plain (30g)", calories: 115, protein: 3, carbs: 22, fat: 1.3, portion: "30g" },
    { id: "sn4", name: "Popcorn Buttered (30g)", calories: 150, protein: 2.5, carbs: 18, fat: 8, portion: "30g" },
    { id: "sn5", name: "Pretzels (30g)", calories: 110, protein: 3, carbs: 23, fat: 1, portion: "30g" },
    { id: "sn6", name: "Crackers (6 pieces)", calories: 120, protein: 2, carbs: 20, fat: 4, portion: "6 pieces" },
    { id: "sn7", name: "Rice Cakes (2 pieces)", calories: 70, protein: 1.4, carbs: 15, fat: 0.5, portion: "2 pieces" },
    { id: "sn8", name: "Cheese Puffs (30g)", calories: 157, protein: 2, carbs: 15, fat: 10, portion: "30g" },
    { id: "sn9", name: "Veggie Chips (30g)", calories: 140, protein: 1, carbs: 18, fat: 7, portion: "30g" },
    { id: "sn10", name: "Beef Jerky (30g)", calories: 82, protein: 13, carbs: 3, fat: 1.8, portion: "30g" },
    { id: "sn11", name: "Protein Bar (1 bar)", calories: 230, protein: 20, carbs: 24, fat: 8, portion: "1 bar" },
    { id: "sn12", name: "Energy Bar (1 bar)", calories: 250, protein: 10, carbs: 35, fat: 8, portion: "1 bar" },
    { id: "sn13", name: "Fruit Leather (1 strip)", calories: 81, protein: 0.5, carbs: 18, fat: 0.8, portion: "1 strip" },
    { id: "sn14", name: "Dark Chocolate Almonds (30g)", calories: 165, protein: 4, carbs: 14, fat: 11, portion: "30g" },
    { id: "sn15", name: "Dried Seaweed (10g)", calories: 25, protein: 2, carbs: 3, fat: 0.5, portion: "10g" },
    { id: "sn16", name: "Breadsticks (2 pieces)", calories: 82, protein: 2.5, carbs: 14, fat: 1.5, portion: "2 pieces" },
    { id: "sn17", name: "Nachos with Cheese (1 serving)", calories: 346, protein: 9, carbs: 36, fat: 19, portion: "1 serving" },
    { id: "sn18", name: "French Fries (medium)", calories: 378, protein: 4, carbs: 44, fat: 20, portion: "medium" },
    { id: "sn19", name: "Onion Rings (6 pieces)", calories: 276, protein: 4, carbs: 31, fat: 16, portion: "6 pieces" },
    { id: "sn20", name: "Edamame Snack (100g)", calories: 122, protein: 11, carbs: 10, fat: 5, portion: "100g" },
  ],
  "Prepared Meals": [
    { id: "pm1", name: "Pizza Margherita (1 slice)", calories: 272, protein: 12, carbs: 34, fat: 10, portion: "1 slice" },
    { id: "pm2", name: "Pizza Pepperoni (1 slice)", calories: 311, protein: 13, carbs: 34, fat: 14, portion: "1 slice" },
    { id: "pm3", name: "Burger (1 regular)", calories: 540, protein: 25, carbs: 40, fat: 29, portion: "1 burger" },
    { id: "pm4", name: "Cheeseburger (1 regular)", calories: 600, protein: 30, carbs: 41, fat: 33, portion: "1 burger" },
    { id: "pm5", name: "Chicken Sandwich (1 regular)", calories: 410, protein: 28, carbs: 38, fat: 16, portion: "1 sandwich" },
    { id: "pm6", name: "BLT Sandwich (1 regular)", calories: 393, protein: 17, carbs: 35, fat: 20, portion: "1 sandwich" },
    { id: "pm7", name: "Turkey Wrap (1 regular)", calories: 370, protein: 22, carbs: 40, fat: 13, portion: "1 wrap" },
    { id: "pm8", name: "Burrito (1 regular)", calories: 580, protein: 25, carbs: 60, fat: 24, portion: "1 burrito" },
    { id: "pm9", name: "Spaghetti Bolognese (1 serving)", calories: 480, protein: 25, carbs: 55, fat: 16, portion: "1 serving" },
    { id: "pm10", name: "Chicken Stir Fry (1 serving)", calories: 380, protein: 30, carbs: 28, fat: 16, portion: "1 serving" },
    { id: "pm11", name: "Fried Rice (1 serving)", calories: 415, protein: 12, carbs: 55, fat: 16, portion: "1 serving" },
    { id: "pm12", name: "Pad Thai (1 serving)", calories: 510, protein: 20, carbs: 56, fat: 22, portion: "1 serving" },
    { id: "pm13", name: "Chicken Tikka Masala (1 serving)", calories: 450, protein: 28, carbs: 18, fat: 30, portion: "1 serving" },
    { id: "pm14", name: "Grilled Chicken Breast (1 serving)", calories: 284, protein: 53, carbs: 0, fat: 6, portion: "1 serving" },
    { id: "pm15", name: "Fish and Chips (1 serving)", calories: 585, protein: 22, carbs: 50, fat: 32, portion: "1 serving" },
    { id: "pm16", name: "Lasagna (1 serving)", calories: 485, protein: 26, carbs: 38, fat: 24, portion: "1 serving" },
    { id: "pm17", name: "Mac and Cheese (1 serving)", calories: 410, protein: 14, carbs: 42, fat: 22, portion: "1 serving" },
    { id: "pm18", name: "Chicken Quesadilla (1 regular)", calories: 490, protein: 28, carbs: 36, fat: 24, portion: "1 quesadilla" },
    { id: "pm19", name: "Falafel Wrap (1 regular)", calories: 420, protein: 14, carbs: 48, fat: 18, portion: "1 wrap" },
    { id: "pm20", name: "Sushi Roll (6 pieces)", calories: 290, protein: 12, carbs: 38, fat: 8, portion: "6 pieces" },
    { id: "pm21", name: "Ramen Bowl (1 serving)", calories: 480, protein: 18, carbs: 52, fat: 20, portion: "1 serving" },
    { id: "pm22", name: "Poke Bowl (1 serving)", calories: 450, protein: 28, carbs: 48, fat: 14, portion: "1 serving" },
    { id: "pm23", name: "Shawarma (1 regular)", calories: 530, protein: 28, carbs: 42, fat: 26, portion: "1 shawarma" },
    { id: "pm24", name: "Doner Kebab (1 regular)", calories: 510, protein: 25, carbs: 40, fat: 25, portion: "1 kebab" },
    { id: "pm25", name: "Biryani (1 serving)", calories: 490, protein: 20, carbs: 60, fat: 18, portion: "1 serving" },
  ],
  Soups: [
    { id: "sp1", name: "Chicken Noodle Soup (1 cup)", calories: 120, protein: 8, carbs: 12, fat: 4, portion: "1 cup" },
    { id: "sp2", name: "Tomato Soup (1 cup)", calories: 130, protein: 2, carbs: 20, fat: 5, portion: "1 cup" },
    { id: "sp3", name: "Lentil Soup (1 cup)", calories: 180, protein: 10, carbs: 27, fat: 3.5, portion: "1 cup" },
    { id: "sp4", name: "Minestrone (1 cup)", calories: 125, protein: 5, carbs: 20, fat: 3, portion: "1 cup" },
    { id: "sp5", name: "Broccoli Cheese Soup (1 cup)", calories: 230, protein: 9, carbs: 14, fat: 16, portion: "1 cup" },
    { id: "sp6", name: "Mushroom Soup (1 cup)", calories: 190, protein: 3, carbs: 15, fat: 14, portion: "1 cup" },
    { id: "sp7", name: "Clam Chowder (1 cup)", calories: 250, protein: 10, carbs: 20, fat: 15, portion: "1 cup" },
    { id: "sp8", name: "French Onion Soup (1 cup)", calories: 180, protein: 6, carbs: 18, fat: 9, portion: "1 cup" },
    { id: "sp9", name: "Butternut Squash Soup (1 cup)", calories: 140, protein: 3, carbs: 22, fat: 5, portion: "1 cup" },
    { id: "sp10", name: "Miso Soup (1 cup)", calories: 66, protein: 3.2, carbs: 8, fat: 2, portion: "1 cup" },
    { id: "sp11", name: "Pea Soup (1 cup)", calories: 190, protein: 12, carbs: 28, fat: 2, portion: "1 cup" },
    { id: "sp12", name: "Pho (1 bowl)", calories: 350, protein: 20, carbs: 42, fat: 8, portion: "1 bowl" },
    { id: "sp13", name: "Gazpacho (1 cup)", calories: 56, protein: 2, carbs: 10, fat: 0.5, portion: "1 cup" },
    { id: "sp14", name: "Bone Broth (1 cup)", calories: 40, protein: 8, carbs: 0, fat: 0.5, portion: "1 cup" },
    { id: "sp15", name: "Corn Chowder (1 cup)", calories: 210, protein: 6, carbs: 26, fat: 10, portion: "1 cup" },
  ],
  "Condiments & Sauces": [
    { id: "cs1", name: "Ketchup (1 tbsp)", calories: 20, protein: 0, carbs: 5, fat: 0, portion: "1 tbsp" },
    { id: "cs2", name: "Mayonnaise (1 tbsp)", calories: 94, protein: 0.1, carbs: 0.1, fat: 10, portion: "1 tbsp" },
    { id: "cs3", name: "Mustard (1 tbsp)", calories: 10, protein: 0.6, carbs: 0.7, fat: 0.6, portion: "1 tbsp" },
    { id: "cs4", name: "Soy Sauce (1 tbsp)", calories: 9, protein: 1, carbs: 1, fat: 0, portion: "1 tbsp" },
    { id: "cs5", name: "Hot Sauce (1 tbsp)", calories: 3, protein: 0, carbs: 0.7, fat: 0, portion: "1 tbsp" },
    { id: "cs6", name: "BBQ Sauce (2 tbsp)", calories: 52, protein: 0.2, carbs: 13, fat: 0.1, portion: "2 tbsp" },
    { id: "cs7", name: "Ranch Dressing (2 tbsp)", calories: 129, protein: 0.4, carbs: 2, fat: 13, portion: "2 tbsp" },
    { id: "cs8", name: "Italian Dressing (2 tbsp)", calories: 86, protein: 0.1, carbs: 3, fat: 8, portion: "2 tbsp" },
    { id: "cs9", name: "Balsamic Vinegar (1 tbsp)", calories: 14, protein: 0, carbs: 3, fat: 0, portion: "1 tbsp" },
    { id: "cs10", name: "Salsa (2 tbsp)", calories: 10, protein: 0.5, carbs: 2, fat: 0, portion: "2 tbsp" },
    { id: "cs11", name: "Guacamole (2 tbsp)", calories: 50, protein: 0.6, carbs: 3, fat: 4.5, portion: "2 tbsp" },
    { id: "cs12", name: "Hummus (2 tbsp)", calories: 70, protein: 2, carbs: 6, fat: 4, portion: "2 tbsp" },
    { id: "cs13", name: "Pesto (1 tbsp)", calories: 80, protein: 2, carbs: 1, fat: 8, portion: "1 tbsp" },
    { id: "cs14", name: "Teriyaki Sauce (2 tbsp)", calories: 40, protein: 1, carbs: 8, fat: 0, portion: "2 tbsp" },
    { id: "cs15", name: "Sriracha (1 tbsp)", calories: 15, protein: 0.3, carbs: 3, fat: 0.2, portion: "1 tbsp" },
    { id: "cs16", name: "Tzatziki (2 tbsp)", calories: 35, protein: 1.5, carbs: 2, fat: 2.5, portion: "2 tbsp" },
    { id: "cs17", name: "Chimichurri (1 tbsp)", calories: 50, protein: 0.2, carbs: 0.5, fat: 5, portion: "1 tbsp" },
    { id: "cs18", name: "Vinaigrette (2 tbsp)", calories: 90, protein: 0, carbs: 2, fat: 9, portion: "2 tbsp" },
    { id: "cs19", name: "Sweet Chili Sauce (1 tbsp)", calories: 40, protein: 0, carbs: 10, fat: 0, portion: "1 tbsp" },
    { id: "cs20", name: "Tahini Dressing (2 tbsp)", calories: 110, protein: 3, carbs: 4, fat: 10, portion: "2 tbsp" },
  ],
  "Spreads & Dips": [
    { id: "sd1", name: "Hummus (100g)", calories: 166, protein: 8, carbs: 14, fat: 10, portion: "100g" },
    { id: "sd2", name: "Guacamole (100g)", calories: 160, protein: 2, carbs: 9, fat: 15, portion: "100g" },
    { id: "sd3", name: "Baba Ganoush (100g)", calories: 140, protein: 3, carbs: 10, fat: 10, portion: "100g" },
    { id: "sd4", name: "Tzatziki (100g)", calories: 66, protein: 3, carbs: 4, fat: 4, portion: "100g" },
    { id: "sd5", name: "Cream Cheese Dip (100g)", calories: 342, protein: 6, carbs: 4, fat: 34, portion: "100g" },
    { id: "sd6", name: "Spinach Artichoke Dip (100g)", calories: 180, protein: 5, carbs: 10, fat: 14, portion: "100g" },
    { id: "sd7", name: "Salsa (100g)", calories: 36, protein: 2, carbs: 6, fat: 0.2, portion: "100g" },
    { id: "sd8", name: "Bean Dip (100g)", calories: 130, protein: 6, carbs: 16, fat: 4, portion: "100g" },
    { id: "sd9", name: "Pimento Cheese (100g)", calories: 310, protein: 10, carbs: 3, fat: 28, portion: "100g" },
    { id: "sd10", name: "French Onion Dip (100g)", calories: 185, protein: 2, carbs: 6, fat: 17, portion: "100g" },
    { id: "sd11", name: "Fruit Dip (100g)", calories: 220, protein: 2, carbs: 30, fat: 10, portion: "100g" },
    { id: "sd12", name: "Muhammara (100g)", calories: 220, protein: 5, carbs: 12, fat: 17, portion: "100g" },
  ],
  Beverages: [
    { id: "b1", name: "Water (250ml)", calories: 0, protein: 0, carbs: 0, fat: 0, portion: "250ml" },
    { id: "b2", name: "Green Tea (250ml)", calories: 2, protein: 0, carbs: 0, fat: 0, portion: "250ml" },
    { id: "b3", name: "Black Coffee (250ml)", calories: 2, protein: 0.3, carbs: 0, fat: 0, portion: "250ml" },
    { id: "b4", name: "Orange Juice (250ml)", calories: 112, protein: 1.7, carbs: 26, fat: 0.5, portion: "250ml" },
    { id: "b5", name: "Apple Juice (250ml)", calories: 117, protein: 0.2, carbs: 29, fat: 0.3, portion: "250ml" },
    { id: "b6", name: "Coconut Water (250ml)", calories: 46, protein: 1.7, carbs: 9, fat: 0.2, portion: "250ml" },
    { id: "b7", name: "Almond Milk (250ml)", calories: 30, protein: 1, carbs: 1, fat: 2.5, portion: "250ml" },
    { id: "b8", name: "Soy Milk (250ml)", calories: 80, protein: 7, carbs: 4, fat: 4, portion: "250ml" },
    { id: "b9", name: "Oat Milk (250ml)", calories: 120, protein: 3, carbs: 16, fat: 5, portion: "250ml" },
    { id: "b10", name: "Protein Shake (250ml)", calories: 150, protein: 25, carbs: 8, fat: 2, portion: "250ml" },
    { id: "b11", name: "Latte (250ml)", calories: 150, protein: 8, carbs: 15, fat: 6, portion: "250ml" },
    { id: "b12", name: "Cappuccino (250ml)", calories: 120, protein: 6, carbs: 12, fat: 5, portion: "250ml" },
    { id: "b13", name: "Espresso (30ml)", calories: 3, protein: 0.1, carbs: 0.5, fat: 0, portion: "30ml" },
    { id: "b14", name: "Iced Tea (250ml)", calories: 45, protein: 0, carbs: 12, fat: 0, portion: "250ml" },
    { id: "b15", name: "Lemonade (250ml)", calories: 99, protein: 0.2, carbs: 26, fat: 0.1, portion: "250ml" },
    { id: "b16", name: "Smoothie Fruit (350ml)", calories: 230, protein: 3, carbs: 52, fat: 1, portion: "350ml" },
    { id: "b17", name: "Smoothie Green (350ml)", calories: 180, protein: 5, carbs: 38, fat: 2, portion: "350ml" },
    { id: "b18", name: "Kombucha (250ml)", calories: 33, protein: 0, carbs: 7, fat: 0, portion: "250ml" },
    { id: "b19", name: "Sparkling Water (250ml)", calories: 0, protein: 0, carbs: 0, fat: 0, portion: "250ml" },
    { id: "b20", name: "Energy Drink (250ml)", calories: 110, protein: 0, carbs: 28, fat: 0, portion: "250ml" },
    { id: "b21", name: "Cola (250ml)", calories: 105, protein: 0, carbs: 26, fat: 0, portion: "250ml" },
    { id: "b22", name: "Diet Soda (250ml)", calories: 1, protein: 0, carbs: 0, fat: 0, portion: "250ml" },
    { id: "b23", name: "Ginger Beer (250ml)", calories: 124, protein: 0, carbs: 32, fat: 0, portion: "250ml" },
    { id: "b24", name: "Matcha Latte (250ml)", calories: 120, protein: 4, carbs: 16, fat: 4, portion: "250ml" },
    { id: "b25", name: "Chai Latte (250ml)", calories: 180, protein: 4, carbs: 30, fat: 5, portion: "250ml" },
  ],
};

export const FOOD_CATEGORIES = Object.keys(PRESET_FOODS);

// Category icons (emoji-based for food categories)
export const FOOD_CATEGORY_ICONS: Record<string, string> = {
  Proteins: "🥩",
  Seafood: "🦐",
  Fruits: "🍎",
  Vegetables: "🥦",
  Salads: "🥗",
  Nuts: "🥜",
  "Dry Fruits": "🍇",
  Seeds: "🌱",
  Carbs: "🍚",
  "Breads & Bakery": "🍞",
  "Cereals & Breakfast": "🥣",
  Fats: "🫒",
  Dairy: "🧀",
  "Sweets & Desserts": "🍰",
  Snacks: "🍿",
  "Prepared Meals": "🍕",
  Soups: "🍲",
  "Condiments & Sauces": "🫙",
  "Spreads & Dips": "🫕",
  Beverages: "☕",
};

// Per-food icon lookup by keyword matching
const FOOD_ICON_MAP: [string[], string][] = [
  // Proteins
  [["chicken"], "🍗"],
  [["salmon", "tuna", "cod", "shrimp", "sardine", "mackerel", "fish", "tilapia", "trout", "halibut", "sea bass"], "🐟"],
  [["beef", "pork", "steak", "veal", "bison", "venison", "ground beef"], "🥩"],
  [["turkey"], "🦃"],
  [["lamb"], "🍖"],
  [["duck"], "🦆"],
  [["egg"], "🥚"],
  [["omelette", "omelet", "frittata"], "🍳"],
  [["scrambled", "sunny side", "poached egg", "fried egg", "boiled egg", "egg white"], "🍳"],
  [["yogurt", "greek yogurt", "lassi"], "🥛"],
  // Indian & South Asian Foods
  [["paratha", "pratha", "roti", "chapati", "kulcha", "bhatura", "puri", "poori"], "🫓"],
  [["dosa", "uttapam", "appam", "idli", "vada"], "🫓"],
  [["samosa", "pakora", "bhaji", "spring roll", "dumpling", "dim sum", "gyoza", "wonton", "momo", "pierogi", "empanada"], "🥟"],
  [["paneer", "halloumi"], "🧀"],
  [["dal", "daal", "dhal", "rasam", "sambhar"], "🍲"],
  [["chaat", "pav bhaji", "chole"], "🍛"],
  [["raita"], "🥛"],
  [["kheer", "gulab jamun", "jalebi", "ladoo", "barfi", "halwa"], "🍮"],
  [["tofu", "tempeh", "seitan", "edamame"], "🫘"],
  [["whey", "protein shake", "protein bar"], "🥤"],
  [["lentil", "chickpea", "bean", "kidney"], "🫘"],
  [["cottage cheese"], "🧀"],
  [["bacon"], "🥓"],
  [["ham", "salami", "pepperoni", "sausage"], "🌭"],
  // Seafood
  [["lobster"], "🦞"],
  [["crab", "crayfish"], "🦀"],
  [["scallop", "mussel", "oyster", "clam"], "🦪"],
  [["calamari", "octopus", "squid"], "🦑"],
  [["prawn"], "🦐"],
  [["sushi", "sashimi"], "🍣"],
  [["fish stick"], "🐟"],
  [["anchov"], "🐟"],
  // Fruits
  [["apple"], "🍎"],
  [["banana"], "🍌"],
  [["orange", "tangerine", "clementine", "mandarin"], "🍊"],
  [["strawberr"], "🍓"],
  [["blueberr", "blackberr", "raspberr", "boysenberr", "elderberr", "mulberr", "cranberr", "currant", "gooseberr"], "🫐"],
  [["grape", "raisin", "sultana"], "🍇"],
  [["mango"], "🥭"],
  [["pineapple"], "🍍"],
  [["watermelon", "cantaloupe", "honeydew"], "🍉"],
  [["kiwi", "kiwano"], "🥝"],
  [["peach", "nectarine", "apricot"], "🍑"],
  [["pear"], "🍐"],
  [["cherry", "cherries"], "🍒"],
  [["coconut"], "🥥"],
  [["avocado"], "🥑"],
  [["lemon", "lime"], "🍋"],
  [["pomegranate"], "🍎"],
  [["grapefruit"], "🍊"],
  [["plum"], "🍑"],
  [["persimmon", "fig", "date"], "🍈"],
  [["papaya", "guava", "passion", "dragon", "jackfruit", "durian", "longan", "lychee", "rambutan", "star fruit", "soursop", "cherimoya", "custard", "feijoa", "tamarind", "mangosteen", "jujube"], "🍈"],
  // Salads (before vegetables so generic "salad" matches 🥗 not 🥬)
  [["tuna salad"], "🐟"],
  [["chicken caesar", "chicken salad"], "🍗"],
  [["egg salad"], "🥚"],
  [["salad", "caesar", "cobb", "caprese", "waldorf", "nicoise", "tabbouleh", "coleslaw", "fattoush", "kale caesar", "asian sesame"], "🥗"],
  // Vegetables
  [["broccoli"], "🥦"],
  [["spinach", "kale", "lettuce", "cabbage", "bok choy", "collard", "swiss chard", "watercress", "arugula"], "🥬"],
  [["bell pepper", "capsicum", "red pepper", "green pepper", "yellow pepper"], "🫑"],
  [["jalape", "chili pepper", "cayenne", "habanero", "serrano", "pepper flake"], "🌶️"],
  [["carrot", "parsnip"], "🥕"],
  [["tomato"], "🍅"],
  [["cucumber", "zucchini", "squash"], "🥒"],
  [["corn"], "🌽"],
  [["potato", "sweet potato"], "🥔"],
  [["mushroom"], "🍄"],
  [["onion", "garlic", "leek"], "🧅"],
  [["eggplant"], "🍆"],
  [["pea", "green bean", "asparagus", "artichoke", "brussels", "celery", "okra", "fennel"], "🌿"],
  [["beet"], "🫐"],
  [["radish", "turnip", "daikon", "rutabaga"], "🥕"],
  [["pumpkin", "butternut"], "🎃"],
  [["cauliflower", "romanesco"], "🥦"],
  // Nuts
  [["almond"], "🌰"],
  [["walnut", "pecan", "hazelnut", "macadamia", "brazil nut", "chestnut", "mixed nut", "tiger nut"], "🌰"],
  [["cashew"], "🌰"],
  [["pistachio"], "🌰"],
  [["peanut", "pine nut"], "🥜"],
  [["trail mix"], "🥜"],
  // Seeds
  [["chia", "flax", "sunflower", "pumpkin seed", "sesame", "hemp", "poppy", "quinoa seed", "basil seed", "fennel seed", "watermelon seed"], "🌻"],
  // Carbs
  [["rice", "wild rice", "basmati", "jasmine"], "🍚"],
  [["oat", "oatmeal"], "🥣"],
  [["quinoa"], "🍚"],
  [["bread", "pita", "naan", "flatbread"], "🍞"],
  [["pasta", "couscous", "spaghetti", "noodle", "soba", "udon"], "🍝"],
  [["barley", "bulgur", "buckwheat", "millet"], "🌾"],
  [["tortilla"], "🌮"],
  // Breads & Bakery
  [["bagel"], "🥯"],
  [["croissant", "danish", "brioche"], "🥐"],
  [["muffin"], "🧁"],
  [["baguette", "ciabatta", "focaccia"], "🥖"],
  [["sourdough", "pumpernickel", "rye bread", "multigrain"], "🍞"],
  [["cornbread"], "🍞"],
  [["garlic bread"], "🧄"],
  // Cereals & Breakfast
  [["granola", "muesli", "cornflakes", "bran", "cheerios"], "🥣"],
  [["pancake"], "🥞"],
  [["waffle"], "🧇"],
  [["french toast"], "🍞"],
  [["acai", "smoothie bowl"], "🥣"],
  [["porridge", "overnight oat"], "🥣"],
  // Fats
  [["olive oil", "coconut oil", "avocado oil", "sesame oil", "flaxseed oil", "mct oil"], "🫒"],
  [["butter", "ghee"], "🧈"],
  [["peanut butter", "almond butter", "cashew butter", "tahini"], "🥜"],
  // Dairy
  [["milk", "buttermilk", "skim milk", "kefir"], "🥛"],
  [["cheese", "mozzarella", "cheddar", "feta", "parmesan", "goat cheese", "cream cheese", "swiss", "brie", "ricotta", "mascarpone", "pimento"], "🧀"],
  [["sour cream", "heavy cream", "whipped cream"], "🥛"],
  [["ice cream", "gelato"], "🍦"],
  [["frozen yogurt"], "🍦"],
  // Sweets & Desserts
  [["cookie", "oreo", "macaron", "biscotti", "shortbread"], "🍪"],
  [["cake", "cheesecake", "brownie", "tiramisu", "pound cake", "angel food", "lemon drizzle"], "🎂"],
  [["cupcake"], "🧁"],
  [["chocolate", "nutella", "hot chocolate", "cocoa"], "🍫"],
  [["donut", "doughnut"], "🍩"],
  [["cinnamon roll", "danish pastry", "eclair", "scone", "baklava", "croissant"], "🥐"],
  [["ice cream", "gelato", "sorbet", "popsicle", "frozen yogurt"], "🍨"],
  [["candy", "snickers", "gummy", "marshmallow"], "🍬"],
  [["pudding", "cr\u00e8me", "panna cotta", "rice pudding"], "🍮"],
  [["honey"], "🍯"],
  [["jam", "jelly", "maple syrup"], "🍯"],
  // Snacks
  [["chip", "nacho"], "🍟"],
  [["popcorn"], "🍿"],
  [["pretzel"], "🥨"],
  [["cracker", "rice cake", "breadstick"], "🍘"],
  [["jerky"], "🥩"],
  [["french fries"], "🍟"],
  [["onion ring"], "🧅"],
  [["seaweed"], "🌿"],
  // Prepared Meals
  [["pizza"], "🍕"],
  [["burger", "cheeseburger"], "🍔"],
  [["sandwich", "blt"], "🥪"],
  [["wrap", "burrito", "quesadilla", "shawarma", "doner", "kebab"], "🌯"],
  [["spaghetti", "bolognese", "lasagna", "mac and cheese"], "🍝"],
  [["stir fry", "fried rice", "pad thai", "biryani"], "🍛"],
  [["tikka", "curry", "masala"], "🍛"],
  [["fish and chips"], "🐟"],
  [["sushi", "poke bowl"], "🍣"],
  [["ramen", "pho"], "🍜"],
  [["falafel"], "🧆"],
  [["taco"], "🌮"],
  // Soups
  [["soup", "chowder", "broth", "stew", "pho", "gazpacho", "bisque"], "🍲"],
  [["miso"], "🍜"],
  // Condiments & Sauces
  [["ketchup", "bbq sauce", "salsa", "hot sauce", "sriracha", "sweet chili"], "🫙"],
  [["mayo", "mayonnaise", "ranch", "dressing", "vinaigrette"], "🫙"],
  [["mustard"], "🫙"],
  [["soy sauce", "teriyaki"], "🫙"],
  [["pesto", "chimichurri"], "🌿"],
  [["vinegar", "balsamic"], "🫙"],
  // Spreads & Dips
  [["hummus"], "🫘"],
  [["guacamole"], "🥑"],
  [["baba ganoush"], "🍆"],
  [["tzatziki"], "🥛"],
  [["dip"], "🫕"],
  // Beverages
  [["water", "sparkling water"], "💧"],
  [["tea", "green tea", "matcha", "chai"], "🍵"],
  [["coffee", "espresso", "latte", "cappuccino"], "☕"],
  [["juice", "orange juice", "apple juice", "lemonade"], "🧃"],
  [["coconut water"], "🥥"],
  [["almond milk", "soy milk", "oat milk"], "🥛"],
  [["smoothie"], "🥤"],
  [["kombucha"], "🍵"],
  [["energy drink", "cola", "soda", "ginger beer", "diet soda"], "🥤"],
];

export function getFoodIcon(foodName: string, category?: string): string {
  const lower = foodName.toLowerCase();
  for (const [keywords, icon] of FOOD_ICON_MAP) {
    if (keywords.some(kw => lower.includes(kw))) return icon;
  }
  // Fallback to category icon
  if (category && FOOD_CATEGORY_ICONS[category]) return FOOD_CATEGORY_ICONS[category];
  return "🍽️";
}

export const MEAL_ICONS = {
  breakfast: Coffee,
  lunch: Sun,
  dinner: Sunset,
  snack: Cookie,
};

export const MEAL_ICONS_LIST = [
  { id: "breakfast", icon: Coffee, label: "Breakfast" },
  { id: "lunch", icon: Sun, label: "Lunch" },
  { id: "dinner", icon: Sunset, label: "Dinner" },
  { id: "snack", icon: Cookie, label: "Snack" },
];

export const MACRO_COLORS = {
  calories: { from: "from-orange-500", to: "to-red-500", bg: "bg-orange-500", text: "text-orange-400" },
  protein: { from: "from-red-500", to: "to-pink-500", bg: "bg-red-500", text: "text-red-400" },
  carbs: { from: "from-amber-500", to: "to-yellow-500", bg: "bg-amber-500", text: "text-amber-400" },
  fat: { from: "from-purple-500", to: "to-violet-500", bg: "bg-purple-500", text: "text-purple-400" },
};

export const DIET_TYPES = [
  { id: "balanced", label: "Balanced", description: "Equal macros distribution" },
  { id: "high_protein", label: "High Protein", description: "For muscle building" },
  { id: "low_carb", label: "Low Carb", description: "Reduce carbohydrates" },
  { id: "keto", label: "Keto", description: "Very low carb, high fat" },
  { id: "vegan", label: "Vegan", description: "Plant-based only" },
  { id: "mediterranean", label: "Mediterranean", description: "Heart-healthy diet" },
];

export const SHOPPING_CATEGORIES = [
  { id: "produce", label: "Produce", color: "text-green-400" },
  { id: "protein", label: "Protein", color: "text-red-400" },
  { id: "dairy", label: "Dairy", color: "text-blue-400" },
  { id: "grains", label: "Grains", color: "text-amber-400" },
  { id: "pantry", label: "Pantry", color: "text-orange-400" },
  { id: "beverages", label: "Beverages", color: "text-cyan-400" },
  { id: "frozen", label: "Frozen", color: "text-indigo-400" },
  { id: "other", label: "Other", color: "text-slate-400" },
];

export const RECIPE_CATEGORIES = [
  { id: "breakfast", label: "Breakfast" },
  { id: "lunch", label: "Lunch" },
  { id: "dinner", label: "Dinner" },
  { id: "snack", label: "Snack" },
  { id: "dessert", label: "Dessert" },
  { id: "smoothie", label: "Smoothie" },
  { id: "other", label: "Other" },
];

export const DIFFICULTY_LEVELS = [
  { id: "easy", label: "Easy" },
  { id: "medium", label: "Medium" },
  { id: "hard", label: "Hard" },
];

export const DIETARY_FLAGS = [
  { id: "vegetarian", label: "Vegetarian" },
  { id: "vegan", label: "Vegan" },
  { id: "gluten_free", label: "Gluten Free" },
  { id: "dairy_free", label: "Dairy Free" },
  { id: "keto", label: "Keto" },
  { id: "low_carb", label: "Low Carb" },
  { id: "high_protein", label: "High Protein" },
];

export const DEFAULT_NUTRITION_STATS = {
  totalCalories: 0,
  totalProtein: 0,
  totalCarbs: 0,
  totalFat: 0,
  mealsLogged: 0,
  waterGlasses: 0,
};

export const DEFAULT_MACRO_TARGETS = {
  calories: { current: 0, target: 2000, unit: "kcal" },
  protein: { current: 0, target: 120, unit: "g" },
  carbs: { current: 0, target: 200, unit: "g" },
  fat: { current: 0, target: 65, unit: "g" },
};
